"""Production schema stabilization — users.id IDENTITY, payments columns, indexes.

Revision ID: 008
Revises: 007
Create Date: 2025-01-31

Fixes:
- NotNullViolationError users.id (add IDENTITY)
- UndefinedColumnError payments.tariff (add columns)
"""

from typing import Sequence, Union

from alembic import op

revision: str = "008"
down_revision: Union[str, None] = "007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) users.id — GENERATED BY DEFAULT AS IDENTITY
    op.execute("""
        DO $$
        BEGIN
            BEGIN
                ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
            BEGIN
                ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            EXCEPTION WHEN OTHERS THEN
                IF SQLERRM NOT LIKE '%already an identity column%' THEN RAISE; END IF;
            END;
        END $$;
    """)

    # users indexes
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_subscription_until ON users(subscription_until)")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")

    # 2) payments — create if not exists
    op.execute("""
        CREATE TABLE IF NOT EXISTS payments (
            id BIGSERIAL PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            tariff VARCHAR(50) NOT NULL DEFAULT '1_month',
            provider VARCHAR(50) NOT NULL DEFAULT 'card',
            amount INTEGER NOT NULL DEFAULT 0,
            status VARCHAR(50) NOT NULL DEFAULT 'pending',
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)

    # payments — add columns if table existed
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS tariff VARCHAR(50) NOT NULL DEFAULT '1_month'")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider VARCHAR(50) NOT NULL DEFAULT 'card'")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount INTEGER NOT NULL DEFAULT 0")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'pending'")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
    op.execute("ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")

    # Ensure user_id FK (if table existed without it)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'payments'::regclass AND conname LIKE '%user_id%'
            ) THEN
                ALTER TABLE payments
                ADD CONSTRAINT fk_payments_user_id
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
            END IF;
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)

    op.execute("CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status)")

    # 3) habit_logs
    op.execute("ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
    op.execute("CREATE INDEX IF NOT EXISTS idx_habit_logs_user_id ON habit_logs(user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_habit_logs_habit_id ON habit_logs(habit_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_habit_logs_created_at ON habit_logs(created_at)")

    # 4) motivation_phrases
    op.execute("ALTER TABLE motivation_phrases ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")


def downgrade() -> None:
    # Indexes — safe to drop
    op.execute("DROP INDEX IF EXISTS idx_habit_logs_created_at")
    op.execute("DROP INDEX IF EXISTS idx_habit_logs_habit_id")
    op.execute("DROP INDEX IF EXISTS idx_habit_logs_user_id")
    op.execute("DROP INDEX IF EXISTS idx_payments_status")
    op.execute("DROP INDEX IF EXISTS idx_payments_user_id")
    op.execute("DROP INDEX IF EXISTS idx_users_subscription_until")
    op.execute("DROP INDEX IF EXISTS idx_users_telegram_id")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS updated_at")
    op.execute("ALTER TABLE payments DROP COLUMN IF EXISTS updated_at")
    op.execute("ALTER TABLE payments DROP COLUMN IF EXISTS created_at")
    op.execute("ALTER TABLE payments DROP COLUMN IF EXISTS status")
    op.execute("ALTER TABLE payments DROP COLUMN IF EXISTS amount")
    op.execute("ALTER TABLE payments DROP COLUMN IF EXISTS provider")
    op.execute("ALTER TABLE payments DROP COLUMN IF EXISTS tariff")
    op.execute("ALTER TABLE habit_logs DROP COLUMN IF EXISTS created_at")
    op.execute("ALTER TABLE motivation_phrases DROP COLUMN IF EXISTS created_at")
    # Note: Cannot safely remove IDENTITY from users.id without data risk; skip in downgrade
