"""Localized texts by language_code."""

TEXTS = {
    "ru": {
        "lang_prompt": "Выберите язык 🌍",
        "tz_prompt": "Выберите часовой пояс ⏰",
        "main_greeting": "Привет, {name} 👋\n\nЯ рядом, чтобы помочь тебе формировать полезные привычки и мягко напоминать о них в нужное время.\n\nВыбери действие ниже 👇",
        "main_title": "Ваша панель привычек ✨",
        "btn_add_habit": "➕ Добавить привычку",
        "btn_edit_habits": "✏️ Редактировать привычки",
        "btn_my_habits": "📋 Мои привычки",
        "btn_profile": "👤 Мой профиль",
        "btn_premium": "💎 Купить Premium",
        "btn_premium_extend": "💎 Продлить Premium",
        "btn_loyalty": "🌎 Программа лояльности",
        "btn_settings": "⚙️ Настройки",
        "btn_back": "⬅️ Назад",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "Other →",
        "habit_presets": "Выбери привычку из списка или введи свою (Premium)",
        "habit_preset_next": "➡️ Далее",
        "habit_preset_prev": "⬅️ Назад",
        "habit_confirm_preset": "✅ Подтвердить",
        "habit_name_prompt": "Введите название привычки",
        "habit_custom": "✍️ Ввести свою",
        "habit_select_days": "Выбери дни недели",
        "habit_select_time": "Выбери время (24ч)",
        "habit_confirm": "Давай сверим ✍️",
        "habit_created": "Привычка создана 🎉",
        "habit_cancel": "❌ Отменить",
        "reminder_done": "🎉 Сделал(а)",
        "reminder_skip": "❌ Не хочу",
        "reminder_skip_msg": "Это важно для тебя, не забывай 🙂",
        "skip_why": "Почему?",
        "skip_tired": "😴 Tired",
        "skip_sick": "🤒 Sick",
        "skip_no_want": "🙅 Don't want",
        "profile_title": "Рады тебя видеть, {name}!",
        "profile_premium_until": "Подписка активна до: {date}",
        "profile_no_premium": "Подписка: Нет",
        "profile_referrals": "Приглашено друзей: {count}",
        "profile_done": "Сделано: {count}",
        "profile_skipped": "Пропуски: {count}",
        "premium_1m": "1 мес — 199₽",
        "premium_3m": "3 мес — 499₽",
        "premium_6m": "6 мес — 799₽",
        "premium_12m": "12 мес — 1299₽",
        "premium_success": "💎 Premium успешно подключен!",
        "premium_extended": "💎 Premium успешно продлен!",
        "premium_paywall": "Только Premium. Оформи подписку.",
        "settings_tz": "Изменить часовой пояс",
        "settings_lang": "Изменить язык",
        "settings_menu": "Настройки",
        "loyalty_title": "Приглашай друзей — получай 7 дней Premium за каждого.",
        "loyalty_link": "Твоя ссылка:",
        "notification_format": "Привычка: {title}\nВремя: {time}",
    },
    "en": {
        "lang_prompt": "Choose language 🌍",
        "tz_prompt": "Choose your timezone ⏰",
        "main_greeting": "Hi, {name} 👋\n\nI'm here to help you build good habits and gently remind you at the right time.\n\nChoose an action below 👇",
        "main_title": "Your habit dashboard ✨",
        "btn_add_habit": "➕ Add Habit",
        "btn_edit_habits": "✏️ Edit Habits",
        "btn_my_habits": "📋 My Habits",
        "btn_profile": "👤 My Profile",
        "btn_premium": "💎 Buy Premium",
        "btn_premium_extend": "💎 Extend Premium",
        "btn_loyalty": "🌎 Loyalty Program",
        "btn_settings": "⚙️ Settings",
        "btn_back": "⬅️ Back",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "Other →",
        "habit_presets": "Choose a habit or enter your own (Premium)",
        "habit_preset_next": "➡️ Next",
        "habit_preset_prev": "⬅️ Back",
        "habit_confirm_preset": "✅ Confirm",
        "habit_name_prompt": "Enter habit name",
        "habit_custom": "✍️ Enter custom",
        "habit_select_days": "Select weekdays",
        "habit_select_time": "Select time (24h)",
        "habit_confirm": "Let's confirm ✍️",
        "habit_created": "Habit created 🎉",
        "habit_cancel": "❌ Cancel",
        "reminder_done": "🎉 Done",
        "reminder_skip": "❌ Skip",
        "reminder_skip_msg": "This matters for you, don't forget 🙂",
        "skip_why": "Why?",
        "skip_tired": "😴 Tired",
        "skip_sick": "🤒 Sick",
        "skip_no_want": "🙅 Don't want",
        "profile_title": "Nice to see you, {name}!",
        "profile_premium_until": "Premium until: {date}",
        "profile_no_premium": "Premium: No",
        "profile_referrals": "Friends invited: {count}",
        "profile_done": "Done: {count}",
        "profile_skipped": "Skipped: {count}",
        "premium_1m": "1 month — 199₽",
        "premium_3m": "3 months — 499₽",
        "premium_6m": "6 months — 799₽",
        "premium_12m": "12 months — 1299₽",
        "premium_success": "💎 Premium activated!",
        "premium_extended": "💎 Premium extended!",
        "premium_paywall": "Premium only. Subscribe to unlock.",
        "settings_tz": "Change timezone",
        "settings_lang": "Change language",
        "settings_menu": "Settings",
        "loyalty_title": "Invite friends — get 7 days Premium for each.",
        "loyalty_link": "Your link:",
        "notification_format": "Habit: {title}\nTime: {time}",
    },
}

SUPPORT_URL = "https://t.me/asc_support"


def t(lang: str, key: str) -> str:
    return TEXTS.get(lang, TEXTS["en"]).get(key, key)
