"""Localized texts by language_code."""

TEXTS = {
    "ru": {
        "lang_prompt": "Выберите язык 🌍",
        "lang_ru": "🇷🇺 Русский",
        "lang_en": "🇬🇧 English",
        "tz_prompt": "Выберите часовой пояс ⏰",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "Other →",
        "main_title": "Ваша панель привычек ✨",
        "btn_add_habit": "➕ Add Habit",
        "btn_my_habits": "📋 My Habits",
        "btn_profile": "👤 Profile",
        "btn_settings": "⚙ Settings",
        "btn_subscription": "💎 Subscription",
        "btn_support": "🎧 Support",
        "btn_back": "🔙 Back",
        "habit_name_prompt": "Введите название привычки",
        "habit_time_prompt": "Выберите время напоминания (ЧЧ:ММ)",
        "habit_created": "Привычка создана 🎉",
        "reminder_done": "✅ Done",
        "reminder_skip": "❌ Skip",
        "skip_why": "Почему?",
        "skip_tired": "😴 Tired",
        "skip_sick": "🤒 Sick",
        "skip_no_want": "🙅 Don't want",
        "profile_subscription": "Подписка",
        "profile_active": "Дней активно",
        "profile_progress": "Прогресс",
        "profile_missed": "📉 Missed habits",
        "sub_buy_1": "Buy 1 month",
        "sub_buy_3": "Buy 3 months",
        "sub_buy_12": "Buy 12 months",
        "sub_success": "Подписка продлена 🎉",
        "settings_tz": "Change timezone",
        "settings_lang": "Change language",
    },
    "en": {
        "lang_prompt": "Choose language 🌍",
        "lang_ru": "🇷🇺 Русский",
        "lang_en": "🇬🇧 English",
        "tz_prompt": "Choose your timezone ⏰",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "Other →",
        "main_title": "Your habit dashboard ✨",
        "btn_add_habit": "➕ Add Habit",
        "btn_my_habits": "📋 My Habits",
        "btn_profile": "👤 Profile",
        "btn_settings": "⚙ Settings",
        "btn_subscription": "💎 Subscription",
        "btn_support": "🎧 Support",
        "btn_back": "🔙 Back",
        "habit_name_prompt": "Enter habit name",
        "habit_time_prompt": "Choose reminder time (HH:MM)",
        "habit_created": "Habit created 🎉",
        "reminder_done": "✅ Done",
        "reminder_skip": "❌ Skip",
        "skip_why": "Why?",
        "skip_tired": "😴 Tired",
        "skip_sick": "🤒 Sick",
        "skip_no_want": "🙅 Don't want",
        "profile_subscription": "Subscription",
        "profile_active": "Days active",
        "profile_progress": "Progress",
        "profile_missed": "📉 Missed habits",
        "sub_buy_1": "Buy 1 month",
        "sub_buy_3": "Buy 3 months",
        "sub_buy_12": "Buy 12 months",
        "sub_success": "Subscription extended 🎉",
        "settings_tz": "Change timezone",
        "settings_lang": "Change language",
    },
}

SUPPORT_URL = "https://t.me/asc_support"


def t(lang: str, key: str) -> str:
    return TEXTS.get(lang, TEXTS["en"]).get(key, key)
