"""Localized texts by language_code."""

TEXTS = {
    "ru": {
        "lang_prompt": "🌐 Выберите язык интерфейса:",
        "tz_prompt": "Выберите часовой пояс ⏰",
        "main_greeting": "Привет, {name} 👋\n\nЯ рядом, чтобы помочь тебе формировать полезные привычки и мягко напоминать о них в нужное время.\n\nВыбери действие ниже 👇",
        "main_title": "Ваша панель привычек ✨",
        "btn_add_habit": "➕ Добавить привычку",
        "btn_edit_habits": "✏️ Редактировать привычки",
        "btn_my_habits": "📋 Мои привычки",
        "btn_profile": "👤 Мой профиль",
        "btn_premium": "💎 Купить Premium",
        "btn_premium_extend": "💎 Продлить Premium",
        "btn_loyalty": "🌎 Программа лояльности",
        "btn_settings": "⚙️ Настройки",
        "btn_back": "⬅️ Назад",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "🌐 Other",
        "tz_full_prompt": "🌍 Полный список часовых поясов:",
        "tz_updated": "Часовой пояс обновлён ✅",
        "tz_confirmation_message": "🌍 Часовой пояс успешно изменён\n\nТекущий: {tz}",
        "tz_screen_title": "🕒 Ваш часовой пояс:\n\n🟢 {tz}",
        "tz_confirmation_short": "✅ Все уведомления теперь будут приходить по новому времени.",
        "tz_changed_msg": "⏰ Часовой пояс изменён на:\n{label}",
        "tz_invalid": "Неверный часовой пояс",
        "habit_presets": "✨ Выбери привычку из списка или введи свою ✍️\n\nВыбери то, что поможет тебе стать лучше каждый день 🚀",
        "habit_preset_next": "➡️ Далее",
        "habit_preset_prev": "⬅️ Назад",
        "habit_confirm_preset": "✅ Подтвердить",
        "habit_name_prompt": "Введите название привычки",
        "habit_custom": "✍️ Ввести свою",
        "habit_custom_locked": "✍️ Ввести свою 🔒",
        "habit_select_days": "Выбери дни недели",
        "habit_select_time": "Выбери время (24ч)",
        "habit_confirm": "Давай сверим ✍️",
        "habit_created": "Привычка создана 🎉",
        "habit_cancel": "❌ Отменить",
        "reminder_done": "🎉 Сделал(а)",
        "reminder_skip": "❌ Не хочу",
        "reminder_skip_msg": "Это важно для тебя, не забывай 🙂",
        "skip_why": "Почему?",
        "skip_tired": "😴 Tired",
        "skip_sick": "🤒 Sick",
        "skip_no_want": "🙅 Don't want",
        "profile_title": "Рады тебя видеть, {name}!",
        "profile_premium_until": "Подписка активна до: {date}",
        "profile_no_premium": "Подписка: Нет",
        "profile_referrals": "Приглашено друзей: {count}",
        "profile_done": "Сделано: {count}",
        "profile_skipped": "Пропуски: {count}",
        "premium_screen": "💎 Выберите тариф Premium:\n\nБольше дисциплины.\nБольше достижений.\nНикаких ограничений.",
        "premium_1m": "💎 1 мес — 99 ₽",
        "premium_3m": "🔥 3 мес — 269 ₽ (–10%)",
        "premium_6m": "🚀 6 мес — 499 ₽ (–15%)",
        "premium_12m": "👑 12 мес — 829 ₽ (–30%)",
        "premium_success": "💎 Premium успешно подключен!",
        "premium_extended": "💎 Premium успешно продлен!",
        "premium_paywall": "Только Premium. Оформи подписку.",
        "premium_required_upsell": "🔒 Эта функция доступна только в Premium.\n\nОткрой все привычки и создавай свои без ограничений 💎",
        "premium_locked_alert": "Доступно только в Premium 💎",
        "payment_method_prompt": "💳 Выберите способ оплаты:",
        "pay_card": "💳 Карта",
        "pay_crypto": "🌏 Криптовалюта",
        "crypto_network_select_prompt": "₿ Выберите сеть для оплаты:",
        "network_trc20": "🟢 TRC20 (TRON)",
        "network_bep20": "🟡 BEP20 (BSC)",
        "network_erc20": "🔵 ERC20 (Ethereum)",
        "network_ton": "🔷 TON",
        "crypto_invoice": "💳 Оплатите криптовалютой:\n\nАдрес: {address}\nСеть: {network}\nСумма: {amount} {currency}",
        "crypto_invoice_full": "₿ Оплата криптовалютой\n\n💰 Сумма: {amount} USD\n🪙 Валюта: {currency}\n🌐 Сеть: {network}\n📍 Адрес:\n`{address}`\n\n⚠️ Отправляйте строго в сети {network_short}.\nОтправка в другой сети приведёт к потере средств.",
        "crypto_pay_btn": "💳 Перейти к оплате",
        "crypto_underpaid": "⚠️ Получена неполная сумма. Проверьте платёж и повторите при необходимости.",
        "crypto_expired": "❌ Время оплаты истекло.\nВы можете создать новый платёж.",
        "settings_tz": "🌍 Изменить часовой пояс",
        "settings_lang": "🌐 Изменить язык",
        "settings_menu": "⚙️ Настройки",
        "loyalty_title": "🌎 Программа лояльности\n\n🤝 Приглашай друзей и получай 🎁 +7 дней Premium\nза каждого, кто оплатит подписку 💎",
        "loyalty_link": "🔗 Твоя персональная ссылка:",
        "referral_bonus_notify": "🎉 Ваш друг купил Premium!\n\n🎁 Вам начислено +7 дней подписки!",
        "notification_format": "Привычка: {title}\nВремя: {time}",
        "edit_no_habits": "Нет привычек.",
        "habit_label": "Привычка",
        "days_label": "Дни",
        "time_label": "Время",
        "admin_denied": "Ай ай ай, сюда нельзя 😉",
        "lang_updated_ru": "Язык переключен на русский 🇷🇺",
        "lang_updated_en": "Язык переключен на английский 🇬🇧",
        "profile_missed": "Пропущенные",
        "habit_deleted": "✅ Привычка удалена",
        "edit_habit_prompt": "Изменить дни / время / удалить:",
        "edit_days_btn": "Изменить дни",
        "edit_time_btn": "Изменить время",
        "delete_btn": "Удалить",
        "admin_no_habits": "🧪 Нет привычек",
        "admin_habit_deleted": "🗑 Привычка удалена",
        "admin_delete_habit_title": "🧪 Удалить привычку:",
        "admin_panel": "🔐 Админ-панель",
        "admin_stats_title": "📊 Статистика:",
        "admin_stats_users": "Всего пользователей",
        "admin_stats_subs": "Активных подписок",
        "admin_search_prompt": "🔎 Введите ID или @username пользователя:",
        "admin_user_not_found": "❌ Пользователь не найден",
        "admin_grant_prompt": "⏳ Введите срок (пример: 30d, 2m, 10h, 15min):",
        "admin_invalid_format": "❌ Неверный формат. Пример: 30d, 2m, 10h",
        "admin_grant_ok": "✅ Доступ выдан",
        "admin_sub_revoked": "❌ Подписка удалена",
        "admin_btn_users": "👥 Пользователи",
        "admin_btn_stats": "📊 Статистика",
        "admin_btn_my_habits": "🧪 Мои привычки",
        "admin_btn_grant": "✅ Выдать подписку",
        "admin_btn_revoke": "❌ Лишить подписки",
        "admin_btn_delete_user": "🗑 Удалить пользователя",
        "admin_delete_prompt": "Введите Telegram ID пользователя для полного удаления:",
        "admin_delete_confirm": "⚠️ Вы уверены, что хотите удалить ВСЕ данные пользователя {tg_id}?\n\nЭто действие необратимо.\n\nНапишите: ПОДТВЕРЖДАЮ",
        "admin_delete_done": "✅ Пользователь полностью удалён из системы.",
        "admin_delete_not_found": "❌ Пользователь не найден.",
        "admin_delete_cancelled": "Удаление отменено.",
        "admin_delete_id_invalid": "ID должен быть числом.",
        "admin_delete_confirm_keyword": "ПОДТВЕРЖДАЮ",
        "admin_user_label": "Пользователь",
        "admin_reg_label": "Регистрация",
        "admin_sub_label": "Подписка",
        "admin_habits_label": "Активных привычек",
        "admin_sub_active": "Активна до {date}",
        "admin_sub_no": "Нет",
        "level_up": "Поздравляем! Новый уровень",
        "your_level": "Ваш уровень",
        "statistics": "Статистика",
        "done_habits": "Сделано привычек",
        "skipped_habits": "Пропуски",
        "btn_statistics": "📊 Статистика",
        "btn_achievements": "🏆 Достижения",
        "achievements_title": "🏆 Достижения",
        "ach_10_habits": "10 привычек",
        "ach_50_habits": "50 привычек",
        "ach_100_habits": "100 привычек",
        "ach_10_streak": "10 дней подряд",
        "ach_unlocked_msg": "Так держать!",
        "ach_locked_prefix": "Целевое действие для достижения:",
        "ach_prev": "⬅️ Назад",
        "ach_next": "➡️ Далее",
    },
    "en": {
        "lang_prompt": "🌐 Choose interface language:",
        "tz_prompt": "Choose your timezone ⏰",
        "main_greeting": "Hi, {name} 👋\n\nI'm here to help you build good habits and gently remind you at the right time.\n\nChoose an action below 👇",
        "main_title": "Your habit dashboard ✨",
        "btn_add_habit": "➕ Add Habit",
        "btn_edit_habits": "✏️ Edit Habits",
        "btn_my_habits": "📋 My Habits",
        "btn_profile": "👤 My Profile",
        "btn_premium": "💎 Buy Premium",
        "btn_premium_extend": "💎 Extend Premium",
        "btn_loyalty": "🌎 Loyalty Program",
        "btn_settings": "⚙️ Settings",
        "btn_back": "⬅️ Back",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "🌐 Other",
        "tz_full_prompt": "🌍 Full timezone list:",
        "tz_updated": "Timezone updated ✅",
        "tz_confirmation_message": "🌍 Timezone changed successfully\n\nCurrent: {tz}",
        "tz_screen_title": "🕒 Your timezone:\n\n🟢 {tz}",
        "tz_confirmation_short": "✅ All reminders will now follow your new local time.",
        "tz_changed_msg": "⏰ Timezone changed to:\n{label}",
        "tz_invalid": "Invalid timezone",
        "habit_presets": "✨ Choose a habit from the list or enter your own ✍️\n\nChoose what helps you become better every day 🚀",
        "habit_preset_next": "➡️ Next",
        "habit_preset_prev": "⬅️ Back",
        "habit_confirm_preset": "✅ Confirm",
        "habit_name_prompt": "Enter habit name",
        "habit_custom": "✍️ Enter custom",
        "habit_custom_locked": "✍️ Enter custom 🔒",
        "habit_select_days": "Select weekdays",
        "habit_select_time": "Select time (24h)",
        "habit_confirm": "Let's confirm ✍️",
        "habit_created": "Habit created 🎉",
        "habit_cancel": "❌ Cancel",
        "reminder_done": "🎉 Done",
        "reminder_skip": "❌ Skip",
        "reminder_skip_msg": "This matters for you, don't forget 🙂",
        "skip_why": "Why?",
        "skip_tired": "😴 Tired",
        "skip_sick": "🤒 Sick",
        "skip_no_want": "🙅 Don't want",
        "profile_title": "Nice to see you, {name}!",
        "profile_premium_until": "Premium until: {date}",
        "profile_no_premium": "Premium: No",
        "profile_referrals": "Friends invited: {count}",
        "profile_done": "Done: {count}",
        "profile_skipped": "Skipped: {count}",
        "premium_screen": "💎 Choose your Premium plan:\n\nMore discipline.\nMore achievements.\nNo limits.",
        "premium_1m": "💎 1 month — 99 ₽",
        "premium_3m": "🔥 3 months — 269 ₽ (–10%)",
        "premium_6m": "🚀 6 months — 499 ₽ (–15%)",
        "premium_12m": "👑 12 months — 829 ₽ (–30%)",
        "premium_success": "💎 Premium activated!",
        "premium_extended": "💎 Premium extended!",
        "premium_paywall": "Premium only. Subscribe to unlock.",
        "premium_required_upsell": "🔒 This feature is available only in Premium.\n\nUnlock all habits and create your own without limits 💎",
        "premium_locked_alert": "Available only in Premium 💎",
        "payment_method_prompt": "💳 Choose payment method:",
        "pay_card": "💳 Card",
        "pay_crypto": "🌏 Cryptocurrency",
        "crypto_network_select_prompt": "₿ Choose payment network:",
        "network_trc20": "🟢 TRC20 (TRON)",
        "network_bep20": "🟡 BEP20 (BSC)",
        "network_erc20": "🔵 ERC20 (Ethereum)",
        "network_ton": "🔷 TON",
        "crypto_invoice": "💳 Pay with crypto:\n\nAddress: {address}\nNetwork: {network}\nAmount: {amount} {currency}",
        "crypto_invoice_full": "₿ Pay with cryptocurrency\n\n💰 Amount: {amount} USD\n🪙 Currency: {currency}\n🌐 Network: {network}\n📍 Address:\n`{address}`\n\n⚠️ Send strictly on {network_short} network.\nSending to another network will result in loss of funds.",
        "crypto_pay_btn": "💳 Pay now",
        "crypto_underpaid": "⚠️ Underpaid amount received. Check your payment and retry if needed.",
        "crypto_expired": "❌ Payment time expired.\nYou can create a new payment.",
        "settings_tz": "🌍 Change timezone",
        "settings_lang": "🌐 Change language",
        "settings_menu": "⚙️ Settings",
        "loyalty_title": "🌎 Loyalty Program\n\n🤝 Invite friends and get 🎁 +7 days of Premium\nfor each friend who purchases a subscription 💎",
        "loyalty_link": "🔗 Your personal link:",
        "referral_bonus_notify": "🎉 Your friend bought Premium!\n\n🎁 You received +7 days subscription!",
        "notification_format": "Habit: {title}\nTime: {time}",
        "edit_no_habits": "No habits yet.",
        "habit_label": "Habit",
        "days_label": "Days",
        "time_label": "Time",
        "admin_denied": "Access denied 😉",
        "lang_updated_ru": "Language switched to Russian 🇷🇺",
        "lang_updated_en": "Language switched to English 🇬🇧",
        "profile_missed": "Missed",
        "habit_deleted": "✅ Habit deleted",
        "edit_habit_prompt": "Change days / time / delete:",
        "edit_days_btn": "Change days",
        "edit_time_btn": "Change time",
        "delete_btn": "Delete",
        "admin_no_habits": "🧪 No habits",
        "admin_habit_deleted": "🗑 Habit deleted",
        "admin_delete_habit_title": "🧪 Delete habit:",
        "admin_panel": "🔐 Admin Panel",
        "admin_stats_title": "📊 Statistics:",
        "admin_stats_users": "Total users",
        "admin_stats_subs": "Active subscriptions",
        "admin_search_prompt": "🔎 Enter user ID or @username:",
        "admin_user_not_found": "❌ User not found",
        "admin_grant_prompt": "⏳ Enter duration (e.g. 30d, 2m, 10h, 15min):",
        "admin_invalid_format": "❌ Invalid format. Example: 30d, 2m, 10h",
        "admin_grant_ok": "✅ Access granted",
        "admin_sub_revoked": "❌ Subscription revoked",
        "admin_btn_users": "👥 Users",
        "admin_btn_stats": "📊 Statistics",
        "admin_btn_my_habits": "🧪 My habits",
        "admin_btn_grant": "✅ Grant subscription",
        "admin_btn_revoke": "❌ Revoke subscription",
        "admin_btn_delete_user": "🗑 Delete user",
        "admin_delete_prompt": "Enter Telegram ID of user to delete completely:",
        "admin_delete_confirm": "⚠️ Are you sure you want to delete ALL data for user {tg_id}?\n\nThis action is irreversible.\n\nType: CONFIRM",
        "admin_delete_done": "✅ User fully deleted from the system.",
        "admin_delete_not_found": "❌ User not found.",
        "admin_delete_cancelled": "Deletion cancelled.",
        "admin_delete_id_invalid": "ID must be a number.",
        "admin_delete_confirm_keyword": "CONFIRM",
        "admin_user_label": "User",
        "admin_reg_label": "Registered",
        "admin_sub_label": "Subscription",
        "admin_habits_label": "Active habits",
        "admin_sub_active": "Active until {date}",
        "admin_sub_no": "No",
        "level_up": "Congratulations! New level",
        "your_level": "Your level",
        "statistics": "Statistics",
        "done_habits": "Completed habits",
        "skipped_habits": "Skipped",
        "btn_statistics": "📊 Statistics",
        "btn_achievements": "🏆 Achievements",
        "achievements_title": "🏆 Achievements",
        "ach_10_habits": "10 habits",
        "ach_50_habits": "50 habits",
        "ach_100_habits": "100 habits",
        "ach_10_streak": "10 day streak",
        "ach_unlocked_msg": "Keep it up!",
        "ach_locked_prefix": "Requirement:",
        "ach_prev": "⬅️ Prev",
        "ach_next": "➡️ Next",
    },
    "ar": {
        "lang_prompt": "🌐 اختر لغة الواجهة:",
        "tz_prompt": "اختر المنطقة الزمنية ⏰",
        "main_greeting": "أهلاً بك، {name} 👋\n\nأنا هنا لمساعدتك على بناء عادات قوية وتذكيرك بها في الوقت المناسب.\n\nاختر الإجراء 👇",
        "main_title": "لوحة العادات ✨",
        "btn_add_habit": "➕ إضافة عادة",
        "btn_edit_habits": "✏️ تعديل العادات",
        "btn_my_habits": "📋 عاداتي",
        "btn_profile": "👤 ملفي الشخصي",
        "btn_premium": "💎 شراء Premium",
        "btn_premium_extend": "💎 تمديد Premium",
        "btn_loyalty": "🌎 برنامج الولاء",
        "btn_settings": "⚙️ الإعدادات",
        "btn_back": "⬅️ رجوع",
        "tz_utc": "UTC",
        "tz_moscow": "Europe/Moscow",
        "tz_london": "Europe/London",
        "tz_dubai": "Asia/Dubai",
        "tz_almaty": "Asia/Almaty",
        "tz_ny": "America/New_York",
        "tz_other": "🌐 أخرى",
        "tz_full_prompt": "🌍 قائمة المناطق الزمنية:",
        "tz_updated": "تم تحديث المنطقة الزمنية ✅",
        "tz_confirmation_message": "🌍 تم تغيير المنطقة الزمنية بنجاح\n\nالحالية: {tz}",
        "tz_screen_title": "🕒 منطقتك الزمنية:\n\n🟢 {tz}",
        "tz_confirmation_short": "✅ ستصل التذكيرات الآن بالتوقيت الجديد.",
        "tz_changed_msg": "⏰ تم تغيير المنطقة الزمنية إلى:\n{label}",
        "tz_invalid": "منطقة زمنية غير صالحة",
        "habit_presets": "✨ اختر عادة من القائمة أو أضف عادتك ✍️\n\nاختر ما يساعدك على التحسن كل يوم 🚀",
        "habit_preset_next": "➡️ التالي",
        "habit_preset_prev": "⬅️ السابق",
        "habit_confirm_preset": "✅ تأكيد",
        "habit_name_prompt": "أدخل اسم العادة",
        "habit_custom": "✍️ إضافة عادة خاصة",
        "habit_custom_locked": "✍️ إضافة عادة خاصة 🔒",
        "habit_select_days": "اختر أيام الأسبوع",
        "habit_select_time": "اختر الوقت (24 ساعة)",
        "habit_confirm": "تأكيد ✍️",
        "habit_created": "تم إنشاء العادة 🎉",
        "habit_cancel": "❌ إلغاء",
        "reminder_done": "🎉 أنجزت",
        "reminder_skip": "❌ تخطي",
        "reminder_skip_msg": "هذا مهم لك، لا تنسَ 🙂",
        "skip_why": "لماذا؟",
        "skip_tired": "😴 متعب",
        "skip_sick": "🤒 مريض",
        "skip_no_want": "🙅 لا أريد",
        "profile_title": "أهلاً بك، {name}!",
        "profile_premium_until": "الاشتراك فعال حتى: {date}",
        "profile_no_premium": "الاشتراك: لا",
        "profile_referrals": "الأصدقاء المدعوون: {count}",
        "profile_done": "تم: {count}",
        "profile_skipped": "تم التخطي: {count}",
        "premium_screen": "💎 اختر باقة Premium:\n\nمزيد من الانضباط.\nمزيد من الإنجازات.\nبدون حدود.",
        "premium_1m": "💎 شهر واحد — 99 ₽",
        "premium_3m": "🔥 3 أشهر — 269 ₽ (–10%)",
        "premium_6m": "🚀 6 أشهر — 499 ₽ (–15%)",
        "premium_12m": "👑 12 شهرًا — 829 ₽ (–30%)",
        "premium_success": "💎 تم تفعيل Premium بنجاح!",
        "premium_extended": "💎 تم تمديد Premium بنجاح!",
        "premium_paywall": "Premium فقط. اشترك للفتح.",
        "premium_required_upsell": "🔒 هذه الميزة متاحة في Premium فقط.\n\nافتح كل العادات وأنشئ عاداتك بدون حدود 💎",
        "premium_locked_alert": "متاح في Premium فقط 💎",
        "payment_method_prompt": "💳 اختر طريقة الدفع:",
        "pay_card": "💳 بطاقة",
        "pay_crypto": "🌏 عملة رقمية",
        "crypto_network_select_prompt": "₿ اختر شبكة الدفع:",
        "network_trc20": "🟢 TRC20 (TRON)",
        "network_bep20": "🟡 BEP20 (BSC)",
        "network_erc20": "🔵 ERC20 (Ethereum)",
        "network_ton": "🔷 TON",
        "crypto_invoice": "💳 الدفع بعملة رقمية:\n\nالعنوان: {address}\nالشبكة: {network}\nالمبلغ: {amount} {currency}",
        "crypto_invoice_full": "₿ الدفع بعملة رقمية\n\n💰 المبلغ: {amount} USD\n🪙 العملة: {currency}\n🌐 الشبكة: {network}\n📍 العنوان:\n`{address}`\n\n⚠️ أرسل فقط عبر شبكة {network_short}.\nالإرسال إلى شبكة أخرى يؤدي لفقدان الأموال.",
        "crypto_pay_btn": "💳 الانتقال للدفع",
        "crypto_underpaid": "⚠️ تم استلام مبلغ ناقص. تحقق من الدفع وأعد المحاولة عند الحاجة.",
        "crypto_expired": "❌ انتهى وقت الدفع.\nيمكنك إنشاء دفعة جديدة.",
        "settings_tz": "🌍 تغيير المنطقة الزمنية",
        "settings_lang": "🌐 تغيير اللغة",
        "settings_menu": "⚙️ الإعدادات",
        "loyalty_title": "🌎 برنامج الولاء\n\n🤝 ادعُ أصدقاءك واحصل على 🎁 +7 أيام Premium\nلكل صديق يدفع الاشتراك 💎",
        "loyalty_link": "🔗 رابطك الشخصي:",
        "referral_bonus_notify": "🎉 صديقك اشترك في Premium!\n\n🎁 تمت إضافة +7 أيام اشتراك لك!",
        "notification_format": "العادة: {title}\nالوقت: {time}",
        "edit_no_habits": "لا توجد عادات.",
        "habit_label": "العادة",
        "days_label": "الأيام",
        "time_label": "الوقت",
        "admin_denied": "عذراً، هذا القسم غير متاح 😉",
        "lang_updated_ru": "تم التبديل إلى الروسية 🇷🇺",
        "lang_updated_en": "تم التبديل إلى الإنجليزية 🇬🇧",
        "lang_updated_ar": "تم التبديل إلى العربية 🇸🇦",
        "profile_missed": "متأخر",
        "habit_deleted": "✅ تم حذف العادة",
        "edit_habit_prompt": "تغيير الأيام / الوقت / الحذف:",
        "edit_days_btn": "تغيير الأيام",
        "edit_time_btn": "تغيير الوقت",
        "delete_btn": "حذف",
        "admin_no_habits": "🧪 لا عادات",
        "admin_habit_deleted": "🗑 تم حذف العادة",
        "admin_delete_habit_title": "🧪 حذف العادة:",
        "admin_panel": "🔐 لوحة الأدمن",
        "admin_stats_title": "📊 الإحصائيات:",
        "admin_stats_users": "إجمالي المستخدمين",
        "admin_stats_subs": "الاشتراكات النشطة",
        "admin_search_prompt": "🔎 أدخل ID أو @username:",
        "admin_user_not_found": "❌ المستخدم غير موجود",
        "admin_grant_prompt": "⏳ أدخل المدة (مثال: 30d, 2m, 10h):",
        "admin_invalid_format": "❌ تنسيق غير صالح. مثال: 30d, 2m, 10h",
        "admin_grant_ok": "✅ تم منح الوصول",
        "admin_sub_revoked": "❌ تم إلغاء الاشتراك",
        "admin_btn_users": "👥 المستخدمون",
        "admin_btn_stats": "📊 الإحصائيات",
        "admin_btn_my_habits": "🧪 عاداتي",
        "admin_btn_grant": "✅ منح اشتراك",
        "admin_btn_revoke": "❌ إلغاء الاشتراك",
        "admin_btn_delete_user": "🗑 حذف مستخدم",
        "admin_delete_prompt": "أدخل Telegram ID للمستخدم للحذف الكامل:",
        "admin_delete_confirm": "⚠️ هل تريد حذف كل بيانات المستخدم {tg_id}؟\n\nلا يمكن التراجع.\n\nاكتب: تأكيد",
        "admin_delete_done": "✅ تم حذف المستخدم بالكامل.",
        "admin_delete_not_found": "❌ المستخدم غير موجود.",
        "admin_delete_cancelled": "تم إلغاء الحذف.",
        "admin_delete_id_invalid": "يجب أن يكون ID رقماً.",
        "admin_delete_confirm_keyword": "تأكيد",
        "admin_user_label": "المستخدم",
        "admin_reg_label": "التسجيل",
        "admin_sub_label": "الاشتراك",
        "admin_habits_label": "العادات النشطة",
        "admin_sub_active": "نشط حتى {date}",
        "admin_sub_no": "لا",
        "level_up": "مبروك! مستوى جديد",
        "your_level": "مستواك",
        "statistics": "الإحصائيات",
        "done_habits": "العادات المنجزة",
        "skipped_habits": "تم التخطي",
        "btn_statistics": "📊 الإحصائيات",
        "btn_achievements": "🏆 الإنجازات",
        "achievements_title": "🏆 الإنجازات",
        "ach_10_habits": "10 عادات",
        "ach_50_habits": "50 عادة",
        "ach_100_habits": "100 عادة",
        "ach_10_streak": "10 أيام متتالية",
        "ach_unlocked_msg": "واصل التقدم!",
        "ach_locked_prefix": "المطلوب:",
        "ach_prev": "⬅️ السابق",
        "ach_next": "➡️ التالي",
    },
}

SUPPORT_URL = "https://t.me/asc_support"

RTL_MARKER = "\u200F"  # Right-to-Left Embedding


def _normalize_lang(lang: str | None) -> str:
    """Ensure lang is 'ru', 'en' or 'ar'. Default: 'ru'."""
    if not lang:
        return "ru"
    code = (lang or "")[:2].lower()
    if code == "ar":
        return "ar"
    return "en" if code == "en" else "ru"


def t(lang: str, key: str, **kwargs) -> str:
    """Get translated text. Use **kwargs for .format(). RTL prefix for Arabic."""
    lang = _normalize_lang(lang)
    texts = TEXTS.get(lang, TEXTS["ru"])
    text = texts.get(key, TEXTS["ru"].get(key, key))
    if kwargs:
        text = text.format(**kwargs)
    return RTL_MARKER + text if lang == "ar" else text
