-- CRITICAL HOTFIX: Schema drift — production-safe, zero-downtime
-- Run in Railway → PostgreSQL → Query
-- DO NOT DROP tables. Use IF NOT EXISTS.

-- USERS TABLE FIXES
ALTER TABLE users ADD COLUMN IF NOT EXISTS language VARCHAR(5) DEFAULT 'ru';
UPDATE users SET language = 'ru' WHERE language IS NULL OR language NOT IN ('ru','en');
ALTER TABLE users ALTER COLUMN language SET DEFAULT 'ru';
ALTER TABLE users ALTER COLUMN language SET NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_until TIMESTAMPTZ NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_by_id BIGINT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone VARCHAR(50) NOT NULL DEFAULT 'UTC';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- HABITS TABLE FIXES
ALTER TABLE habits ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS is_custom BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- REFERRALS TABLE FIXES
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS inviter_id BIGINT NULL;
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS invited_id BIGINT NULL;
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
