-- CRITICAL PRODUCTION FIX — Run in Railway PostgreSQL → Query
-- ROOT CAUSE: users.id is NOT auto-increment → INSERT returns NULL → crash
-- NO DROPS. NO DATA LOSS.

-- STEP 0: Verify schema (run first to confirm required columns exist)
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'users';
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'payments';

-- 1️⃣ FIX users.id — must be GENERATED BY DEFAULT AS IDENTITY
-- Run these one by one (skip DROP DEFAULT if it errors: "column has no default")
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2️⃣ Ensure primary key exists (skip if already exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'users'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE users ADD PRIMARY KEY (id);
  END IF;
END $$;

-- VERIFY: must see "generated by default as identity"
-- SELECT column_default FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id';

-- 3️⃣ ADD missing tariff column in payments
ALTER TABLE payments
ADD COLUMN IF NOT EXISTS tariff VARCHAR(50) NOT NULL DEFAULT '1_month';

-- 4️⃣ Ensure created_at exists in payments
ALTER TABLE payments
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
