-- PRODUCTION SCHEMA STABILIZATION
-- Run in Railway PostgreSQL → Query
-- Fixes: NotNullViolationError users.id, UndefinedColumnError payments.tariff
-- NO DROPS. NO DATA LOSS.

-- ============================================================
-- 1) USERS.id — must be GENERATED BY DEFAULT AS IDENTITY
-- ============================================================
-- Skip DROP DEFAULT if it errors "column has no default"
DO $$
BEGIN
    ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- Add IDENTITY for auto-increment
DO $$
BEGIN
    ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN OTHERS THEN
    IF SQLERRM NOT LIKE '%already an identity column%' THEN RAISE; END IF;
END $$;

-- Ensure primary key
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'users'::regclass AND contype = 'p'
    ) THEN
        ALTER TABLE users ADD PRIMARY KEY (id);
    END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_users_subscription_until ON users(subscription_until);

-- updated_at (optional, for audit)
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ============================================================
-- 2) PAYMENTS — add missing columns
-- ============================================================
-- Create table if not exists
CREATE TABLE IF NOT EXISTS payments (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tariff VARCHAR(50) NOT NULL DEFAULT '1_month',
    provider VARCHAR(50) NOT NULL DEFAULT 'card',
    amount INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- If table existed, add missing columns
ALTER TABLE payments ADD COLUMN IF NOT EXISTS tariff VARCHAR(50) NOT NULL DEFAULT '1_month';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider VARCHAR(50) NOT NULL DEFAULT 'card';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'pending';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Ensure user_id FK
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'payments'::regclass AND conname LIKE '%user_id%'
    ) THEN
        ALTER TABLE payments
        ADD CONSTRAINT fk_payments_user_id
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);

-- ============================================================
-- 3) HABIT_LOGS — created_at if missing
-- ============================================================
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE INDEX IF NOT EXISTS idx_habit_logs_user_id ON habit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_habit_logs_habit_id ON habit_logs(habit_id);
CREATE INDEX IF NOT EXISTS idx_habit_logs_created_at ON habit_logs(created_at);

-- ============================================================
-- 4) MOTIVATION_PHRASES — created_at if missing
-- ============================================================
ALTER TABLE motivation_phrases ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ============================================================
-- VERIFY (run separately after migration)
-- ============================================================
-- SELECT column_name, column_default FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id';
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'payments';
