"""150 motivational phrases per language — short, loyal, premium tone."""

MOTIVATION_RU = [
    "Молодец!", "Так держать!", "Ты справляешься!", "Отличный шаг!", "Прекрасная работа!",
    "Супер!", "Ты на верном пути!", "Классно!", "Горжусь тобой!", "Отлично!",
    "Это успех!", "Продолжай!", "Ты можешь!", "Замечательно!", "Уверенно!",
    "Отличный выбор!", "Верно!", "Вперед!", "Еще немного!", "Почти!",
    "Прорыв!", "Ты крут!", "Вдохновляешь!", "Отличный темп!", "Так и нужно!",
    "Успех рядом!", "Держи ритм!", "Отличный день!", "Сильно!", "Прогресс есть!",
    "Стабильно!", "Верное решение!", "Отличная дисциплина!", "Браво!", "Так и дальше!",
    "Это уровень!", "Отличная работа!", "Впечатляет!", "Не останавливайся!", "С каждым днем лучше!",
    "Прогрессируешь!", "Уверенный шаг!", "Это результат!", "Ты растешь!", "Отличный настрой!",
    "Прекрасно!", "У тебя получается!", "Четко!", "Идеально!", "Так победим!",
    "Красота!", "Сильнее с каждым днем!", "Правильно!", "Ты звезда!", "Движение вперед!",
    "Отличный результат!", "Ты в форме!", "Так держи!", "Прорыв!", "Молодец!",
    "Великолепно!", "Ты на высоте!", "Невероятно!", "Победа!", "Ты лучший!",
    "Продолжаем!", "Вдохновляет!", "Сильнее!", "Ты справляешься!", "Удачи!",
    "Надежный!", "Ты круче!", "Дерзай!", "Здорово!", "Расти дальше!",
    "Ты молодец!", "Отлично!", "Красота!", "Сильно!", "Так и дальше!",
    "Вперед!", "Ты справляешься!", "Молодец!", "Горжусь!", "Супер!",
    "Продолжай!", "Ты можешь!", "Отличный шаг!", "Так держать!", "Верно!",
    "Прогресс!", "Это успех!", "Уверенно!", "Классно!", "Замечательно!",
    "Держи ритм!", "Отличный темп!", "Почти!", "Еще немного!", "Прорыв!",
    "Вдохновляешь!", "Ты крут!", "Стабильно!", "Браво!", "Идеально!",
    "У тебя получается!", "Отличный день!", "Сильно!", "Продолжай в том же духе!",
    "Ты на верном пути!", "Отличная дисциплина!", "Верное решение!", "Так и нужно!",
    "Успех рядом!", "Прогресс есть!", "Отличный выбор!", "Ты растешь!", "Это результат!",
    "Уверенный шаг!", "Прогрессируешь!", "С каждым днем лучше!", "Не останавливайся!",
    "Впечатляет!", "Отличная работа!", "Это уровень!", "Так и дальше!", "Отличная дисциплина!",
    "Браво!", "Верное решение!", "Стабильно!", "Прогресс есть!", "Отличный день!",
    "Сильно!", "Держи ритм!", "Успех рядом!", "Так и нужно!", "Вдохновляешь!",
    "Ты крут!", "Прорыв!", "Еще немного!", "Почти!", "Верно!",
    "Вперед!", "Отличный выбор!", "Уверенно!", "Классно!", "Замечательно!",
    "Ты на высоте!", "Не сдавайся!", "Победа за тобой!",
]

MOTIVATION_EN = [
    "Well done!", "Keep it up!", "You're doing it!", "Great step!", "Great job!",
    "Super!", "You're on the right path!", "Nice!", "Proud of you!", "Excellent!",
    "That's success!", "Keep going!", "You can do it!", "Wonderful!", "Confidently!",
    "Great choice!", "Right!", "Go!", "Almost there!", "Almost!",
    "Breakthrough!", "You're awesome!", "Inspiring!", "Great pace!", "That's the way!",
    "Success is near!", "Keep the rhythm!", "Great day!", "Strong!", "Progress!",
    "Steady!", "Right decision!", "Great discipline!", "Bravo!", "Keep it up!",
    "That's level!", "Great work!", "Impressive!", "Don't stop!", "Better every day!",
    "Progressing!", "Confident step!", "That's a result!", "You're growing!", "Great mindset!",
    "Wonderful!", "You're getting it!", "Clean!", "Perfect!", "We'll win!",
    "Beautiful!", "Stronger every day!", "Right!", "You're a star!", "Moving forward!",
    "Great result!", "You're in shape!", "Keep it!", "Breakthrough!", "Well done!",
    "Magnificent!", "You're on top!", "Incredible!", "Victory!", "You're the best!",
    "Let's continue!", "Inspiring!", "Stronger!", "You're doing it!", "Good luck!",
    "Reliable!", "You're cooler!", "Dare!", "Great!", "Grow further!",
    "You're great!", "Excellent!", "Beautiful!", "Strong!", "Keep it up!",
    "Go!", "You're doing it!", "Well done!", "Proud!", "Super!",
    "Keep going!", "You can!", "Great step!", "Keep it up!", "Right!",
    "Progress!", "That's success!", "Confidently!", "Nice!", "Wonderful!",
    "Keep the rhythm!", "Great pace!", "Almost!", "Almost there!", "Breakthrough!",
    "Inspiring!", "You're awesome!", "Steady!", "Bravo!", "Perfect!",
    "You're getting it!", "Great day!", "Strong!", "Keep it up!",
    "You're on the right path!", "Great discipline!", "Right decision!", "That's the way!",
    "Success is near!", "Progress!", "Great choice!", "You're growing!", "That's a result!",
    "Confident step!", "Progressing!", "Better every day!", "Don't stop!",
    "Impressive!", "Great work!", "That's level!", "Keep it up!", "Great discipline!",
    "Bravo!", "Right decision!", "Steady!", "Progress!", "Great day!",
    "Strong!", "Keep the rhythm!", "Success is near!", "That's the way!", "Inspiring!",
    "You're awesome!", "Breakthrough!", "Almost there!", "Almost!", "Right!",
    "Go!", "Great choice!", "Confidently!", "Nice!", "Wonderful!",
    "You're on top!", "Don't give up!", "Victory is yours!",
]
